# Generated by Django 6.0.7 on 2026-07-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Task",
        ),
    ]
